### ISSUE TITLE
curl cache

### ISSUE THREAD

**Issue by QuentinGruber** [H1emu/H1emu-server-app#9]
curl should not use cached data

**Comment by Z1Meme** [comment]
CREDIT: RuhhRohh#5827 (Discord)

"the curl parameter Cache Control doesn't always work because of the server can ignore it, instead you have to specify a different query string everytime
could use random, or set the query string to the time of query
so for example
https://h1emu.s3.eu-west-3.amazonaws.com/patch/dinput8.dll?6:00
should fix your problems
itll treat it like a unique url
just make sure that every time the command is called it has a different query inserted
also could keep the Cache-Control I am sure it would add extra capability"

**Comment by QuentinGruber** [comment]
fixed in v1.1.1
